-- Migration: 000_base_schema.sql
-- Purpose: Create core tables that were missing from migrations
-- These tables are required by the application and referenced by other migrations

-- ============================================================
-- DEVICE REGISTRY (provisioned devices)
-- ============================================================
CREATE TABLE IF NOT EXISTS device_registry (
    tenant_id       TEXT NOT NULL,
    device_id       TEXT NOT NULL,
    site_id         TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE, REVOKED, PENDING
    provision_token TEXT,
    provision_token_hash TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata        JSONB NOT NULL DEFAULT '{}',
    PRIMARY KEY (tenant_id, device_id)
);

CREATE INDEX IF NOT EXISTS idx_device_registry_site ON device_registry(tenant_id, site_id);
CREATE INDEX IF NOT EXISTS idx_device_registry_token ON device_registry(provision_token_hash) WHERE provision_token_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_device_registry_status ON device_registry(tenant_id, status);

-- ============================================================
-- DEVICE STATE (runtime state of devices)
-- ============================================================
CREATE TABLE IF NOT EXISTS device_state (
    tenant_id            TEXT NOT NULL,
    site_id              TEXT NOT NULL,
    device_id            TEXT NOT NULL,
    status               TEXT NOT NULL DEFAULT 'OFFLINE',  -- ONLINE, STALE, OFFLINE
    last_heartbeat_at    TIMESTAMPTZ NULL,
    last_telemetry_at    TIMESTAMPTZ NULL,
    last_seen_at         TIMESTAMPTZ NULL,
    last_state_change_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    state                JSONB NOT NULL DEFAULT '{}',
    PRIMARY KEY (tenant_id, device_id)
);

CREATE INDEX IF NOT EXISTS idx_device_state_site ON device_state(tenant_id, site_id);
CREATE INDEX IF NOT EXISTS idx_device_state_status ON device_state(tenant_id, status);

-- ============================================================
-- FLEET ALERT (alerts generated by evaluator)
-- ============================================================
CREATE TABLE IF NOT EXISTS fleet_alert (
    id          BIGSERIAL PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at   TIMESTAMPTZ NULL,
    tenant_id   TEXT NOT NULL,
    site_id     TEXT NOT NULL,
    device_id   TEXT NOT NULL,
    alert_type  TEXT NOT NULL,
    fingerprint TEXT NOT NULL DEFAULT '',
    status      TEXT NOT NULL DEFAULT 'OPEN',  -- OPEN, ACKNOWLEDGED, CLOSED
    severity    INTEGER NOT NULL DEFAULT 0,
    confidence  REAL NOT NULL DEFAULT 0.0,
    summary     TEXT NOT NULL,
    details     JSONB NOT NULL DEFAULT '{}'
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fleet_alert_open_uq
    ON fleet_alert(tenant_id, fingerprint) WHERE status = 'OPEN';
CREATE INDEX IF NOT EXISTS idx_fleet_alert_tenant ON fleet_alert(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_fleet_alert_device ON fleet_alert(tenant_id, device_id);
CREATE INDEX IF NOT EXISTS idx_fleet_alert_created ON fleet_alert(created_at DESC);

-- ============================================================
-- ALERT RULES (user-defined alerting rules)
-- ============================================================
CREATE TABLE IF NOT EXISTS alert_rules (
    id          SERIAL PRIMARY KEY,
    tenant_id   TEXT NOT NULL,
    name        TEXT NOT NULL,
    description TEXT,
    enabled     BOOLEAN NOT NULL DEFAULT true,
    rule_type   TEXT NOT NULL DEFAULT 'threshold',  -- threshold, anomaly, pattern
    conditions  JSONB NOT NULL DEFAULT '{}',
    actions     JSONB NOT NULL DEFAULT '[]',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_alert_rules_tenant ON alert_rules(tenant_id);
CREATE INDEX IF NOT EXISTS idx_alert_rules_enabled ON alert_rules(tenant_id, enabled);

-- ============================================================
-- QUARANTINE (rejected/invalid messages)
-- ============================================================
CREATE TABLE IF NOT EXISTS quarantine_events (
    id          BIGSERIAL PRIMARY KEY,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    event_ts    TIMESTAMPTZ NULL,
    topic       TEXT NOT NULL,
    tenant_id   TEXT NULL,
    site_id     TEXT NULL,
    device_id   TEXT NULL,
    msg_type    TEXT NULL,
    reason      TEXT NOT NULL,
    payload     JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_quarantine_device ON quarantine_events(device_id);
CREATE INDEX IF NOT EXISTS idx_quarantine_ingested ON quarantine_events(ingested_at DESC);
CREATE INDEX IF NOT EXISTS idx_quarantine_tenant ON quarantine_events(tenant_id);

-- ============================================================
-- QUARANTINE COUNTERS (aggregated stats)
-- ============================================================
CREATE TABLE IF NOT EXISTS quarantine_counters_minute (
    bucket_minute TIMESTAMPTZ NOT NULL,
    tenant_id     TEXT NOT NULL,
    reason        TEXT NOT NULL,
    cnt           BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (bucket_minute, tenant_id, reason)
);

CREATE INDEX IF NOT EXISTS idx_quarantine_counters_tenant
    ON quarantine_counters_minute(tenant_id, bucket_minute DESC);

-- ============================================================
-- APP SETTINGS (global configuration)
-- ============================================================
CREATE TABLE IF NOT EXISTS app_settings (
    key        TEXT NOT NULL PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Insert default settings
INSERT INTO app_settings (key, value) VALUES
    ('MODE', 'DEV'),
    ('STORE_REJECTS', '1'),
    ('MIRROR_REJECTS_TO_RAW', '0'),
    ('RATE_LIMIT_RPS', '10'),
    ('RATE_LIMIT_BURST', '50'),
    ('MAX_PAYLOAD_BYTES', '16384')
ON CONFLICT (key) DO NOTHING;

-- ============================================================
-- Verify tables created
-- ============================================================
DO $$
BEGIN
    RAISE NOTICE 'Base schema tables created successfully';
END $$;
